### GENERAL SETTINGS ###

# Site settings
title: Talent @ Slaay
description: "Bringing the best of Goan talent to you!"
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "/talent" #important: start with /
url: "http://talent.slaaysourcecoders.in"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

disqus_shortname: "talentatslaay"
disqus_site_shortname: "talentatslaay"

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: facebook
    url: https://www.facebook.com/slaaysourcecoders
  - title: twitter
    url: https://twitter.com/slaaysrcecoders
  - title: linkedin
    url: http://in.linkedin.com/in/presleydias
    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - Cuncolim,
    - Pin 403703, GOA
    - India.
email: presley.diaslee@gmail.com
tel: +91 Presley!


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
members:
  - name: Presley Dias
    position: Co-Founder
    text: I am Presley Dias, a software engineer by profession. I love to experiment with different technologies in my free time (http://slaay.github.io/) 
    img: team01.jpg
    social:
      - title: envelope #use for email address
        url: mailto:presley.diaslee@gmail.com
      - title: twitter
        url: http://twitter.com/slaaysrcecoders
  - name: Edviges Fernandes
    position: Co-Founder
    text: A software developer who has experience in web based applications.
    img: team02.png
    social:
      # - title: envelope #use for email address
      #   url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/slaaysrcecoders
  - name: Casburn Noronha
    position: The Enforcer
    text: The dude with an attitude, Still only a teenager. Looking to spread his wings into the world of engineering.
    img: team03.jpg
    social:
      - title: envelope #use for email address
        url: mailto:casburn.noronha@gmail.com
      - title: twitter
        url: http://twitter.com/slaaysrcecoders
  # - name: Martin Blunt
  #   position: Marketing
  #   text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
  #   img: team04.jpg
  #   social:
  #     - title: envelope #use for email address
  #       url: mailto:name@domain.com
  #     - title: twitter
  #       url: http://twitter.com/handle
    
# Clients information. Shown on Home and About pages.
clients:
  - name: CUHSS
    img: 1.png
  - name: OLHS
    img: 2.png
  # - name: Vimeo
  #   img: client03.png
  # - name: VimeoPro
  #   img: client04.png
    
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "I believe in learning when ever and where ever I can. 
I also believe that I need to give back to the society. 
I am blessed with a loving, caring and generous family who has alway supported me in what ever I do. 
So besides making websites for schools, I also open to conduct workshops for school or college students. 
Adopt an institute and fully automate the working of the institue. 
Help the teachers to make education fun and help the students to make learning fun!"

#Testimonial content. Shown on Home and About page. 
testimonial:
    message: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged."
    author: Marcel Newman
    position: WEB DESIGNER - BLACKTIE.CO


